/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JniFuncMain */

#ifndef _Included_JniFuncMain
#define _Included_JniFuncMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JniFuncMain
 * Method:    foo
 * Signature: ()V
 */
JNIEXPORT void JNICALL foo (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
